task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 7
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./datasets/SAR-AIRcraft-1.0/images/train/
    ann_file: ./datasets/SAR-AIRcraft-1.0/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./datasets/SAR-AIRcraft-1.0/images/val/
    ann_file: ./datasets/SAR-AIRcraft-1.0/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction


test_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./datasets/SAR-AIRcraft-1.0/images/test/
    ann_file: ./datasets/SAR-AIRcraft-1.0/annotations/instances_test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
