task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 7
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/Biubush/Archives/Documents/Datasets/SAR-AIRcraft-1.0/JPEGImages/
    ann_file: D:/Biubush/Archives/Documents/Datasets/SAR-AIRcraft-1.0-COCO/train_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/Biubush/Archives/Documents/Datasets/SAR-AIRcraft-1.0/JPEGImages/
    ann_file: D:/Biubush/Archives/Documents/Datasets/SAR-AIRcraft-1.0-COCO/val_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
