# SAR飞机检测优化配置
# 整合了多项优化措施：学习率策略改进、训练迭代优化、领域适应性增强、损失函数调整

__include__: [
  '../../dataset/sar_airplane_detection.yml',
  '../../runtime.yml',
  '../include/dataloader.yml',
  '../include/optimizer_improved.yml',  # 使用优化后的学习率策略
  '../include/dfine_hgnetv2.yml',
]

project_name: "SAR-Aircraft-Detection"
exp_name: "sar_dfine_optimized"
output_dir: ./output/sar_dfine_optimized

# 模型配置
DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B4'  # 使用L型号，平衡性能和速度
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

DFINETransformer:
  num_layers: 4  # 增加层数提高模型能力
  eval_idx: -1

HybridEncoder:
  in_channels: [256, 512, 1024]
  hidden_dim: 256
  depth_mult: 0.34
  expansion: 0.5

# 使用SAR图像特定的损失函数
DFINECriterion:
  type: SARDFINECriterion  # 使用SAR优化的损失函数
  losses: ['focal', 'boxes', 'fgl', 'ddf', 'edge']  # 添加边缘感知损失
  giou_weight: 2.5  # 增加GIoU损失权重
  bbox_weight: 2.0  # 增加边界框损失权重
  small_object_scale: 1.5  # 小目标损失缩放因子
  weight_dict:
    loss_focal: 2.0
    loss_giou: 2.0
    loss_bbox: 5.0
    loss_fgl: 1.0
    loss_ddf: 1.0
    loss_edge: 1.0  # 边缘感知损失权重

# 训练配置
epochs: 500  # 增加训练轮次
train_dataloader:
  total_batch_size: 32  # 保持批量大小适中，确保稳定训练
  dataset:
    transforms:
      type: Compose
      ops:
        - type: RandomRotate  # 随机旋转
          prob: 0.5
          max_angle: 15
        - type: RandomHorizontalFlip  # 水平翻转
          prob: 0.5
        - type: RandomVerticalFlip  # 垂直翻转
          prob: 0.3
        - type: SARSpeckleNoise  # SAR特有的斑点噪声增强
          prob: 0.4
          intensity: 0.15
        - type: SARHistogramEqualization  # SAR图像直方图均衡化
          prob: 0.5
          clip_limit: 2.0
        - type: SAREdgeEnhancement  # SAR图像边缘增强
          prob: 0.4
          alpha: 0.4
        - type: SARBrightness  # SAR图像亮度调整
          prob: 0.4
          factor_range: [0.7, 1.3]
        - type: RandomErasing  # 随机擦除，增强模型鲁棒性
          prob: 0.2
      policy:
        epoch: 100  # 适应余弦退火学习率

  collate_fn:
    stop_epoch: 200  # 第一阶段训练持续时间
    ema_restart_decay: 0.9999
    base_size_repeat: 8

val_dataloader:
  total_batch_size: 32

# 早停策略优化
early_stop:
  patience: 30  # 降低早停耐心参数
  min_delta: 0.0005  # 提高精度要求
  min_epochs: 50  # 确保至少训练50轮
  monitor: 'AP50:95'  # 监控mAP指标 